version: "3.7"
services:
  tester:
    image: gcr.io/nnyn-dev/preemptible-tester2/tester:latest
    build:
      context: .
      target: tester
  observer:
    image: gcr.io/nnyn-dev/preemptible-tester2/observer:latest
    build:
      context: .
      target: observer
