apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: observer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: observer
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: observer
