apiVersion: apps/v1
kind: Deployment
metadata:
  name: tester
spec:
  selector:
    matchLabels:
      app: tester
  replicas: 1
  template:
    metadata:
      labels:
        app: tester
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: preemptible
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "preemptible"
          effect: "NoSchedule"
      containers:
        - name: tester
          readinessProbe:
            tcpSocket:
              port: 10000
            periodSeconds: 1
          image: gcr.io/nnyn-dev/preemptible-tester2/tester:latest
          command: ["./tester"]
          imagePullPolicy: Always
          resources:
            requests:
              memory: "32Mi"
              cpu: "20m"
